// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwRJVnu8etUI7Q7rG7fdAz5fU8I-41hGQ',
    appId: '1:319250424761:web:5cc45bb05a2998a3ff0c68',
    messagingSenderId: '319250424761',
    projectId: 'yoggo-52562',
    authDomain: 'yoggo-52562.firebaseapp.com',
    storageBucket: 'yoggo-52562.appspot.com',
    measurementId: 'G-7G410MS122',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6CrV3UOVYO_OPZLH6_JLxiTee17qibbA',
    appId: '1:319250424761:android:b8ca2f1c873bdd64ff0c68',
    messagingSenderId: '319250424761',
    projectId: 'yoggo-52562',
    storageBucket: 'yoggo-52562.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-p4eACfNA151rFQdQX4KWsG9Ojeoh_JU',
    appId: '1:319250424761:ios:a2190473e27718ddff0c68',
    messagingSenderId: '319250424761',
    projectId: 'yoggo-52562',
    storageBucket: 'yoggo-52562.appspot.com',
    iosClientId: '319250424761-8egfk3m4cld29b3is7bc7l3od1i30e5p.apps.googleusercontent.com',
    iosBundleId: 'com.example.yoggo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-p4eACfNA151rFQdQX4KWsG9Ojeoh_JU',
    appId: '1:319250424761:ios:f85f9af7b957777eff0c68',
    messagingSenderId: '319250424761',
    projectId: 'yoggo-52562',
    storageBucket: 'yoggo-52562.appspot.com',
    iosClientId: '319250424761-umudl2ujikcrapno02bvdu5dlkuoes70.apps.googleusercontent.com',
    iosBundleId: 'com.example.yoggo.RunnerTests',
  );
}
