// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALewl_voCtUNwFIHApU8rOvK-1EBGrzz0',
    appId: '1:127586410541:android:f0d6e0a409f5c2be5a18a4',
    messagingSenderId: '127586410541',
    projectId: 'lovel-a2507',
    storageBucket: 'lovel-a2507.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMf-2QU9mI-H4GNwR-eVOh99GOH1Ws3K0',
    appId: '1:127586410541:ios:2d4f2ba269d6417e5a18a4',
    messagingSenderId: '127586410541',
    projectId: 'lovel-a2507',
    storageBucket: 'lovel-a2507.appspot.com',
    androidClientId:
        '127586410541-70861lai2h86ald7qtbk2c3f4jiqs9cm.apps.googleusercontent.com',
    iosClientId:
        '127586410541-r15cjul2ouodd4feg8cm4sf2l08hbrui.apps.googleusercontent.com',
    iosBundleId: 'com.sayit.yoggo',
  );
}
